/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author chars_mc
 */
public class vCalculator extends javax.swing.JFrame {

  /**
   * @return the operation
   */
  public javax.swing.JComboBox<String> getOperation() {
    return operation;
  }

  /**
   * @return the calcBtn
   */
  public javax.swing.JToggleButton getCalcBtn() {
    return calcBtn;
  }

  /**
   * @return the a
   */
  public javax.swing.JTextField getA() {
    return a;
  }

  /**
   * @return the b
   */
  public javax.swing.JTextField getB() {
    return b;
  }

  /**
   * @return the result
   */
  public javax.swing.JLabel getResult() {
    return result;
  }

  /**
   * Creates new form vCalculator
   */
  public vCalculator() {
    initComponents();
    
    // center the window
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    title = new javax.swing.JLabel();
    result = new javax.swing.JLabel();
    a = new javax.swing.JTextField();
    b = new javax.swing.JTextField();
    calcBtn = new javax.swing.JToggleButton();
    operation = new javax.swing.JComboBox<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Calculator");
    setBackground(new java.awt.Color(26, 28, 35));

    jPanel1.setBackground(new java.awt.Color(26, 28, 35));
    jPanel1.setForeground(new java.awt.Color(33, 191, 194));
    jPanel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N

    title.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
    title.setForeground(new java.awt.Color(33, 191, 194));
    title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    title.setText("CALCULATOR");

    result.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
    result.setForeground(new java.awt.Color(250, 183, 149));
    result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    result.setText("Result: ");
    result.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 183, 149), 1, true));

    a.setBackground(new java.awt.Color(26, 28, 35));
    a.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
    a.setForeground(new java.awt.Color(39, 215, 150));
    a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    a.setText("Number 1");
    a.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 215, 150)));
    a.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        aFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        aFocusLost(evt);
      }
    });
    a.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        aActionPerformed(evt);
      }
    });

    b.setBackground(new java.awt.Color(26, 28, 35));
    b.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
    b.setForeground(new java.awt.Color(39, 215, 150));
    b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    b.setText("Number 2");
    b.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 215, 150)));
    b.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        bFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        bFocusLost(evt);
      }
    });

    calcBtn.setBackground(new java.awt.Color(39, 215, 150));
    calcBtn.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
    calcBtn.setForeground(new java.awt.Color(26, 28, 35));
    calcBtn.setText("CALCULATE");
    calcBtn.setBorder(null);
    calcBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        calcBtnActionPerformed(evt);
      }
    });

    operation.setBackground(new java.awt.Color(26, 28, 35));
    operation.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
    operation.setForeground(new java.awt.Color(250, 194, 154));
    operation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add", "Substract", "Multiply", "Divide", "Exponentation", "Factorial", "Module" }));
    operation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 194, 154)));
    operation.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    operation.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        operationActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(operation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(calcBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(operation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(calcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(27, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_aActionPerformed

  private void calcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBtnActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_calcBtnActionPerformed

  private void operationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationActionPerformed
    String actualOperation = operation.getSelectedItem().toString();
    if(actualOperation.equals("Factorial")) b.setEnabled(false);
    else b.setEnabled(true);
  }//GEN-LAST:event_operationActionPerformed

  private void aFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aFocusGained
    // TODO add your handling code here:
    if(a.getText().equals("Number 1")) a.setText("");
  }//GEN-LAST:event_aFocusGained

  private void aFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aFocusLost
    // TODO add your handling code here:
    if(a.getText().equals("")) a.setText("Number 1");
  }//GEN-LAST:event_aFocusLost

  private void bFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bFocusGained
    // TODO add your handling code here:
    if(b.getText().equals("Number 2")) b.setText("");
  }//GEN-LAST:event_bFocusGained

  private void bFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bFocusLost
    // TODO add your handling code here:
    if(b.getText().equals("")) b.setText("Number 2");
  }//GEN-LAST:event_bFocusLost

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(vCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(vCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(vCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(vCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new vCalculator().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField a;
  private javax.swing.JTextField b;
  private javax.swing.JToggleButton calcBtn;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JComboBox<String> operation;
  private javax.swing.JLabel result;
  private javax.swing.JLabel title;
  // End of variables declaration//GEN-END:variables
}
